from hypermagnetics.sources import configure


def create_data(
    n_eval: int = 8,
    n_ensemble: int = 5,
    min_sources: int = 10,
    step_sources: int = 250,
    field_eval: bool = False,
    grid_eval: bool = False,
    seed: int = 42,
    shape: str = "prism",
    quadtree: bool = True,
    name: str = "eval",
    res: int = 32,
    lim: float = 1.0,
    eps: float = 0.0,
    max_size: float = 0.5,
    min_size: float = 0.05,
    batch_size: int = 1000,
    dp_correction: bool = True,
    size_log: bool = True,
    r0_gap: bool = False,
    target_source: bool = False,
    p_target_source: float = 1.0,
    start_idx: int = 0,
):
    for n in range(start_idx, n_eval + 1):
        source_config = {
            "shape": shape,
            "n_samples": n_ensemble,
            "n_sources": max(min_sources, step_sources * n),
            "lim": lim,
            "res": res,
            "target_source": target_source,
            "p_target_source": p_target_source,
            "eps": eps,
            "grid_eval": grid_eval,
            "field_eval": field_eval,
            "quadtree": quadtree,
            "save_data": True,
            "db_prefix": name,
            "seed": seed,
            "min_size": min_size,
            "max_size": max_size,
            "size_log": size_log,
            "r0_gap": r0_gap,
            "batch_size": batch_size,
            "dipole_correction": dp_correction,
        }
        configure(**source_config)


if __name__ == "__main__":
    res = 32
    lim = 1.2
    # for p in [0, 0.1, 0.25, 0.5, 0.75, 0.99]:
    name = "eval_large_m"
    # create_data(
    #     n_eval=0,
    #     n_ensemble=10,
    #     min_sources=49,
    #     step_sources=250,
    #     field_eval=True,
    #     name=f"eval_{name}",
    #     shape="prism",
    #     quadtree=False,
    #     grid_eval=True,
    #     res=res,
    #     lim=lim,
    #     eps=0.0,
    #     max_size=0.48,
    #     min_size=0.12,
    #     batch_size=1,
    #     seed=42,
    #     dp_correction=False,
    #     size_log=False,
    #     r0_gap=True,
    #     target_source=True,
    #     start_idx=0,
    # )

    create_data(
        n_eval=0,
        n_ensemble=1000,
        min_sources=1,
        step_sources=0,
        field_eval=True,
        name=f"val_{name}",
        shape="prism",
        quadtree=False,
        grid_eval=True,
        res=res,
        lim=lim,
        eps=0.0,
        max_size=0.48,
        min_size=0.12,
        batch_size=30,
        seed=92,
        dp_correction=False,
        size_log=False,
        r0_gap=True,
        target_source=True,
    )

    # create_data(
    #     n_eval=0,
    #     n_ensemble=1000,
    #     min_sources=10,
    #     step_sources=0,
    #     field_eval=True,
    #     name=f"val_{name}",
    #     shape="prism",
    #     quadtree=True,
    #     grid_eval=True,
    #     res=res,
    #     lim=lim,
    #     eps=0.0,
    #     max_size=0.5,
    #     min_size=0.1,
    #     batch_size=30,
    #     seed=41,
    #     dp_correction=False,
    # )

    # create_data(
    #     n_eval=0,
    #     n_ensemble=200000,
    #     min_sources=1,
    #     step_sources=0,
    #     field_eval=True,
    #     name=f"train_{name}",
    #     shape="prism",
    #     quadtree=False,
    #     grid_eval=True,
    #     res=res,
    #     lim=lim,
    #     eps=0.0,
    #     max_size=0.5,
    #     min_size=0.05,
    #     batch_size=40,
    #     seed=42,
    #     dp_correction=False,
    #     r0_gap=True,
    #     size_log=False,
    # )
