source:
  n_samples: 1
  n_sources: 1
  lim: 3
  res: 64
model:
  width: 1024
  depth: 3
  hwidth: 2
  hdepth: 2
schedule:
  - epochs: 5000
    params:
      learning_rate: 0.01
  - epochs: 5000
    params:
      learning_rate: 0.001
  - epochs: 5000
    params:
      learning_rate: 0.0001
  - epochs: 5000
    params:
      learning_rate: 0.00001
