window_params: &window_params
  lim: 3
  res: 32
  shape: prism
  dim: 3

sample_params: &sample_params
  <<: *window_params
  n_samples: 100
  n_sources: 1

hmodel_params: &hmodel_params
  hwidth: 0.25
  hdepth: 3

sources:
  train:
    <<: *sample_params
    seed: 100
  test:
    <<: *sample_params
    seed: 101
  val-single:
    <<: *window_params
    n_samples: 1
    n_sources: 1
    res: 50
    seed: 102
  val-multi:
    <<: *window_params
    n_samples: 1
    n_sources: 4
    res: 50
    seed: 102

model:
  hyperlayer:
    <<: *hmodel_params
    in_size: 3
    width: 50
    depth: 3
    seed: 41
  # fourier:
  #   <<: *hmodel_params
  #   order: 32
  #   seed: 42
  # hypernetwork:
  #   <<: *hmodel_params
  #   width: 20
  #   depth: 3
  #   seed: 43

schedule:
  # - epochs: 5000
  #   params:
  #     learning_rate: 0.01
  # - epochs: 5000
  #   params:
  #     learning_rate: 0.001
  - epochs: 25000
    params:
      learning_rate: 0.00005
  # - epochs: 5000
  #   params:
  #     learning_rate: 0.00001
