source:
  n_samples: 5000
  lim: 3
  res: 16
model:
  width: 1024
  depth: 3
  hwidth: 2
  hdepth: 2
schedule:
  - epochs: 5000
    params:
      learning_rate: 0.005
  - epochs: 5000
    params:
      learning_rate: 0.0005
  - epochs: 5000
    params:
      learning_rate: 0.00005
  - epochs: 5000
    params:
      learning_rate: 0.000005
