sample_params: &sample_params
  lim: 3
  res: 32

hmodel_params: &hmodel_params
  hwidth: 1
  hdepth: 3

sources:
  train:
    <<: *sample_params
    n_samples: 10000
    n_sources: 1
    seed: 100
  test:
    <<: *sample_params
    n_samples: 1000
    n_sources: 4
    seed: 101
  val:
    <<: *sample_params
    n_samples: 1
    n_sources: 4
    res: 128
    seed: 102

model:
  hyperlayer:
    <<: *hmodel_params
    width: 400
    depth: 3
    seed: 41
  fourier:
    <<: *hmodel_params
    order: 16
    seed: 42

schedule:
  - epochs: 5000
    params:
      learning_rate: 0.01
  - epochs: 5000
    params:
      learning_rate: 0.001
  - epochs: 5000
    params:
      learning_rate: 0.0001
  - epochs: 5000
    params:
      learning_rate: 0.00001
