program: trainer.py
method: bayes
metric:
  name: val_acc
  goal: minimize
parameters:
  source:
    parameters:
      n_samples:
        value: 1000
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        value: 64
  model:
    parameters:
      width:
        value: 20
      depth:
        value: 3
      hdepth:
        value: 3
  trainer:
    parameters:
      learning_rate:
        min: 0.00001
        max: 0.01
      epochs:
        value: 3000
run_cap: 10
