program: trainer.py
method: bayes
metric:
  name: val_acc
  goal: minimize
parameters:
  source:
    parameters:
      n_samples:
        value: 1000
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        values: [32, 64, 128]
  model:
    parameters:
      width:
        value: 20
      depth:
        value: 3
      hdepth:
        value: 2
  trainer:
    parameters:
      learning_rate:
        min: 1e-4
        max: 5e-2
      momentum:
        min: 0.8
        max: 0.9999
      epochs:
        value: 5000
run_cap: 500
