program: sweeper.py
method: grid
name: varying-width-adam
metric:
  name: val_acc
  goal: minimize
parameters:
  source:
    parameters:
      n_samples:
        value: 10000
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        value: 32
  model:
    parameters:
      width:
        value: 30 
      depth:
        values: [2, 3, 4]
      hdepth:
        value: 2
  trainer:
    parameters:
      learning_rate:
        value: 1e-5
      momentum:
        value: 0.998
      epochs:
        value: 5000
run_cap: 25
