program: trainer.py
method: bayes
metric:
  name: val_acc
  goal: minimize
parameters:
  source:
    parameters:
      n_samples:
        value: 1000
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        value: 64
  model:
    parameters:
      width:
        min: 8
        max: 48
      depth:
        min: 2
        max: 4
      hdepth:
        min: 1
        max: 4
  trainer:
    parameters:
      learning_rate:
        value: 0.0005
      epochs:
        value: 3000
run_cap: 500
