program: trainer.py
method: bayes
metric:
  name: val_acc
  goal: minimize
parameters:
  learning_rate:
    min: 0.00001
    max: 0.01
  width:
    values: [4, 8, 16]
  depth:
    values: [2, 3]
  hdepth:
    value: 2
  res:
    values: [16, 32, 64]
run_cap: 100