program: trainer.py
method: bayes
metric:
  name: val_acc
  goal: minimize
parameters:
  source:
    parameters:
      n_samples:
        value: 2000
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        value: 64
  model:
    parameters:
      width:
        min: 8
        max: 32
      depth:
        min: 2
        max: 5
      hdepth:
        min: 2
        max: 5
  trainer:
    parameters:
      learning_rate:
        value: 0.005
      epochs:
        value: 3000
run_cap: 100
