program: trainer.py
method: grid
parameters:
  source:
    parameters:
      n_samples:
        value: 500
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        values: [16, 32, 64]
  model:
    parameters:
      width:
        values: [4, 8, 16]
      depth:
        values: [2, 3]
      hdepth:
        value: 2
  trainer:
    parameters:
      learning_rate:
        values: [0.01, 0.001, 0.0001]
      epochs:
        value: 2000
