program: sweeper.py
method: bayes
name: varying-learning-rate
metric:
  name: val_acc
  goal: minimize
parameters:
  source:
    parameters:
      n_samples:
        value: 5000
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        value: 32
  model:
    parameters:
      width:
        value: 20
      depth:
        value: 3
      hwidth: # Factor by which to multiply nparams
        value: 2
      hdepth:
        value: 2
  trainer:
    parameters:
      log_learning_rate:
        min: -6.01
        max: -4.01
      epochs:
        value: 5000
run_cap: 25
