program: sweeper.py
method: grid
name: varying-width-adam
metric:
  name: val_acc
  goal: minimize
parameters:
  source:
    parameters:
      n_samples:
        value: 1000
      n_sources:
        value: 2
      lim:
        value: 3
      res:
        value: 32
  model:
    parameters:
      width:
        value: 20
      depth:
        value: 3
      hwidth: # Factor by which to multiply nparams
        value: 2
      hdepth:
        value: 2
  trainer:
    parameters:
      learning_rate:
        values: [1e-4, 1e-5]
      momentum:
        value: 0.998
      epochs:
        value: 500
run_cap: 25
